services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api-proximamente"
    hostname: "api-proximamente"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
      - dbs
      - automation

networks:
  proxy:
    external: true
  dbs:
    external: true
  automation:
    external: true
